// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type BatasTanah struct {
	ID           int64           `json:"id"`
	BerkasID     int64           `json:"berkas_id"`
	Arah         string          `json:"arah"`
	NamaPemilik  string          `json:"nama_pemilik"`
	NamaNormal   string          `json:"nama_normal"`
	PanjangMeter sql.NullFloat64 `json:"panjang_meter"`
}

type BerkasTanah struct {
	ID                int64           `json:"id"`
	Tahun             int64           `json:"tahun"`
	Urutan            int64           `json:"urutan"`
	NomorBerkas       string          `json:"nomor_berkas"`
	TanggalSurat      string          `json:"tanggal_surat"`
	P1Nama            string          `json:"p1_nama"`
	P1Umur            sql.NullInt64   `json:"p1_umur"`
	P1Nik             string          `json:"p1_nik"`
	P1Pekerjaan       sql.NullString  `json:"p1_pekerjaan"`
	P1Alamat          sql.NullString  `json:"p1_alamat"`
	P2Nama            sql.NullString  `json:"p2_nama"`
	P2Alamat          sql.NullString  `json:"p2_alamat"`
	KelurahanID       int64           `json:"kelurahan_id"`
	JalanGang         string          `json:"jalan_gang"`
	Rt                string          `json:"rt"`
	LuasM2            float64         `json:"luas_m2"`
	LuasGantiRugiM2   sql.NullFloat64 `json:"luas_ganti_rugi_m2"`
	TglPengukuran     sql.NullString  `json:"tgl_pengukuran"`
	JuruUkurKelID     sql.NullInt64   `json:"juru_ukur_kel_id"`
	JuruUkurKecID     sql.NullInt64   `json:"juru_ukur_kec_id"`
	LurahID           sql.NullInt64   `json:"lurah_id"`
	KetuaRtID         sql.NullInt64   `json:"ketua_rt_id"`
	IndukID           sql.NullInt64   `json:"induk_id"`
	ArsipLama         int64           `json:"arsip_lama"`
	DupKey            string          `json:"dup_key"`
	DupOverrideAlasan sql.NullString  `json:"dup_override_alasan"`
	DupOverrideBy     sql.NullInt64   `json:"dup_override_by"`
	DupOverrideAt     sql.NullString  `json:"dup_override_at"`
	Status            string          `json:"status"`
	CreatedBy         sql.NullInt64   `json:"created_by"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type JuruUkur struct {
	ID          int64         `json:"id"`
	Tingkat     string        `json:"tingkat"`
	KelurahanID sql.NullInt64 `json:"kelurahan_id"`
	Nama        string        `json:"nama"`
	Nip         string        `json:"nip"`
	Aktif       int64         `json:"aktif"`
}

type Kelurahan struct {
	ID    int64  `json:"id"`
	Nama  string `json:"nama"`
	Aktif int64  `json:"aktif"`
}

type KetuaRT struct {
	ID          int64  `json:"id"`
	KelurahanID int64  `json:"kelurahan_id"`
	NomorRt     string `json:"nomor_rt"`
	Nama        string `json:"nama"`
	Aktif       int64  `json:"aktif"`
}

type Lurah struct {
	ID          int64  `json:"id"`
	KelurahanID int64  `json:"kelurahan_id"`
	Nama        string `json:"nama"`
	Nip         string `json:"nip"`
	Aktif       int64  `json:"aktif"`
}

type Pengaturan struct {
	ID               int64          `json:"id"`
	Kecamatan        sql.NullString `json:"kecamatan"`
	Kota             sql.NullString `json:"kota"`
	KantorPertanahan sql.NullString `json:"kantor_pertanahan"`
}

type SaksiSempadan struct {
	ID       int64  `json:"id"`
	BerkasID int64  `json:"berkas_id"`
	Urutan   int64  `json:"urutan"`
	Nama     string `json:"nama"`
}

type User struct {
	ID                 int64  `json:"id"`
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	Nama               string `json:"nama"`
	Role               string `json:"role"`
	MustChangePassword int64  `json:"must_change_password"`
	CreatedAt          string `json:"created_at"`
}
