// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countKelurahan = `-- name: CountKelurahan :one

SELECT COUNT(*) FROM kelurahan
`

// ===== KELURAHAN =====
func (q *Queries) CountKelurahan(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKelurahan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBerkas = `-- name: CreateBerkas :one
INSERT INTO berkas_tanah (
    tahun, urutan, nomor_berkas, tanggal_surat,
    p1_nama, p1_umur, p1_nik, p1_pekerjaan, p1_alamat,
    p2_nama, p2_alamat,
    kelurahan_id, jalan_gang, rt, luas_m2, luas_ganti_rugi_m2,
    tgl_pengukuran, juru_ukur_kel_id, juru_ukur_kec_id,
    lurah_id, ketua_rt_id, induk_id, arsip_lama,
    dup_key, dup_override_alasan, dup_override_by, dup_override_at,
    created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, tahun, urutan, nomor_berkas, tanggal_surat, p1_nama, p1_umur, p1_nik, p1_pekerjaan, p1_alamat, p2_nama, p2_alamat, kelurahan_id, jalan_gang, rt, luas_m2, luas_ganti_rugi_m2, tgl_pengukuran, juru_ukur_kel_id, juru_ukur_kec_id, lurah_id, ketua_rt_id, induk_id, arsip_lama, dup_key, dup_override_alasan, dup_override_by, dup_override_at, status, created_by, created_at, updated_at
`

type CreateBerkasParams struct {
	Tahun             int64           `json:"tahun"`
	Urutan            int64           `json:"urutan"`
	NomorBerkas       string          `json:"nomor_berkas"`
	TanggalSurat      string          `json:"tanggal_surat"`
	P1Nama            string          `json:"p1_nama"`
	P1Umur            sql.NullInt64   `json:"p1_umur"`
	P1Nik             string          `json:"p1_nik"`
	P1Pekerjaan       sql.NullString  `json:"p1_pekerjaan"`
	P1Alamat          sql.NullString  `json:"p1_alamat"`
	P2Nama            sql.NullString  `json:"p2_nama"`
	P2Alamat          sql.NullString  `json:"p2_alamat"`
	KelurahanID       int64           `json:"kelurahan_id"`
	JalanGang         string          `json:"jalan_gang"`
	Rt                string          `json:"rt"`
	LuasM2            float64         `json:"luas_m2"`
	LuasGantiRugiM2   sql.NullFloat64 `json:"luas_ganti_rugi_m2"`
	TglPengukuran     sql.NullString  `json:"tgl_pengukuran"`
	JuruUkurKelID     sql.NullInt64   `json:"juru_ukur_kel_id"`
	JuruUkurKecID     sql.NullInt64   `json:"juru_ukur_kec_id"`
	LurahID           sql.NullInt64   `json:"lurah_id"`
	KetuaRtID         sql.NullInt64   `json:"ketua_rt_id"`
	IndukID           sql.NullInt64   `json:"induk_id"`
	ArsipLama         int64           `json:"arsip_lama"`
	DupKey            string          `json:"dup_key"`
	DupOverrideAlasan sql.NullString  `json:"dup_override_alasan"`
	DupOverrideBy     sql.NullInt64   `json:"dup_override_by"`
	DupOverrideAt     sql.NullString  `json:"dup_override_at"`
	CreatedBy         sql.NullInt64   `json:"created_by"`
}

func (q *Queries) CreateBerkas(ctx context.Context, arg CreateBerkasParams) (BerkasTanah, error) {
	row := q.db.QueryRowContext(ctx, createBerkas,
		arg.Tahun,
		arg.Urutan,
		arg.NomorBerkas,
		arg.TanggalSurat,
		arg.P1Nama,
		arg.P1Umur,
		arg.P1Nik,
		arg.P1Pekerjaan,
		arg.P1Alamat,
		arg.P2Nama,
		arg.P2Alamat,
		arg.KelurahanID,
		arg.JalanGang,
		arg.Rt,
		arg.LuasM2,
		arg.LuasGantiRugiM2,
		arg.TglPengukuran,
		arg.JuruUkurKelID,
		arg.JuruUkurKecID,
		arg.LurahID,
		arg.KetuaRtID,
		arg.IndukID,
		arg.ArsipLama,
		arg.DupKey,
		arg.DupOverrideAlasan,
		arg.DupOverrideBy,
		arg.DupOverrideAt,
		arg.CreatedBy,
	)
	var i BerkasTanah
	err := row.Scan(
		&i.ID,
		&i.Tahun,
		&i.Urutan,
		&i.NomorBerkas,
		&i.TanggalSurat,
		&i.P1Nama,
		&i.P1Umur,
		&i.P1Nik,
		&i.P1Pekerjaan,
		&i.P1Alamat,
		&i.P2Nama,
		&i.P2Alamat,
		&i.KelurahanID,
		&i.JalanGang,
		&i.Rt,
		&i.LuasM2,
		&i.LuasGantiRugiM2,
		&i.TglPengukuran,
		&i.JuruUkurKelID,
		&i.JuruUkurKecID,
		&i.LurahID,
		&i.KetuaRtID,
		&i.IndukID,
		&i.ArsipLama,
		&i.DupKey,
		&i.DupOverrideAlasan,
		&i.DupOverrideBy,
		&i.DupOverrideAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJuruUkur = `-- name: CreateJuruUkur :one
INSERT INTO juru_ukur (tingkat, kelurahan_id, nama, nip, aktif) VALUES (?, ?, ?, ?, ?) RETURNING id, tingkat, kelurahan_id, nama, nip, aktif
`

type CreateJuruUkurParams struct {
	Tingkat     string        `json:"tingkat"`
	KelurahanID sql.NullInt64 `json:"kelurahan_id"`
	Nama        string        `json:"nama"`
	Nip         string        `json:"nip"`
	Aktif       int64         `json:"aktif"`
}

func (q *Queries) CreateJuruUkur(ctx context.Context, arg CreateJuruUkurParams) (JuruUkur, error) {
	row := q.db.QueryRowContext(ctx, createJuruUkur,
		arg.Tingkat,
		arg.KelurahanID,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
	)
	var i JuruUkur
	err := row.Scan(
		&i.ID,
		&i.Tingkat,
		&i.KelurahanID,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
	)
	return i, err
}

const createKelurahan = `-- name: CreateKelurahan :one
INSERT INTO kelurahan (nama, aktif) VALUES (?, 1) RETURNING id, nama, aktif
`

func (q *Queries) CreateKelurahan(ctx context.Context, nama string) (Kelurahan, error) {
	row := q.db.QueryRowContext(ctx, createKelurahan, nama)
	var i Kelurahan
	err := row.Scan(&i.ID, &i.Nama, &i.Aktif)
	return i, err
}

const createKetuaRT = `-- name: CreateKetuaRT :one
INSERT INTO ketua_rt (kelurahan_id, nomor_rt, nama, aktif) VALUES (?, ?, ?, ?) RETURNING id, kelurahan_id, nomor_rt, nama, aktif
`

type CreateKetuaRTParams struct {
	KelurahanID int64  `json:"kelurahan_id"`
	NomorRt     string `json:"nomor_rt"`
	Nama        string `json:"nama"`
	Aktif       int64  `json:"aktif"`
}

func (q *Queries) CreateKetuaRT(ctx context.Context, arg CreateKetuaRTParams) (KetuaRT, error) {
	row := q.db.QueryRowContext(ctx, createKetuaRT,
		arg.KelurahanID,
		arg.NomorRt,
		arg.Nama,
		arg.Aktif,
	)
	var i KetuaRT
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.NomorRt,
		&i.Nama,
		&i.Aktif,
	)
	return i, err
}

const createLurah = `-- name: CreateLurah :one
INSERT INTO lurah (kelurahan_id, nama, nip, aktif) VALUES (?, ?, ?, ?) RETURNING id, kelurahan_id, nama, nip, aktif
`

type CreateLurahParams struct {
	KelurahanID int64  `json:"kelurahan_id"`
	Nama        string `json:"nama"`
	Nip         string `json:"nip"`
	Aktif       int64  `json:"aktif"`
}

func (q *Queries) CreateLurah(ctx context.Context, arg CreateLurahParams) (Lurah, error) {
	row := q.db.QueryRowContext(ctx, createLurah,
		arg.KelurahanID,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
	)
	var i Lurah
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, nama, role, must_change_password)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, password_hash, nama, role, must_change_password, created_at
`

type CreateUserParams struct {
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	Nama               string `json:"nama"`
	Role               string `json:"role"`
	MustChangePassword int64  `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Nama,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateLurahByKelurahan = `-- name: DeactivateLurahByKelurahan :exec
UPDATE lurah SET aktif = 0 WHERE kelurahan_id = ?
`

func (q *Queries) DeactivateLurahByKelurahan(ctx context.Context, kelurahanID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateLurahByKelurahan, kelurahanID)
	return err
}

const deleteBatasByBerkas = `-- name: DeleteBatasByBerkas :exec
DELETE FROM batas_tanah WHERE berkas_id = ?
`

func (q *Queries) DeleteBatasByBerkas(ctx context.Context, berkasID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBatasByBerkas, berkasID)
	return err
}

const deleteJuruUkur = `-- name: DeleteJuruUkur :exec
DELETE FROM juru_ukur WHERE id = ?
`

func (q *Queries) DeleteJuruUkur(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJuruUkur, id)
	return err
}

const deleteKelurahan = `-- name: DeleteKelurahan :exec
DELETE FROM kelurahan WHERE id = ?
`

func (q *Queries) DeleteKelurahan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKelurahan, id)
	return err
}

const deleteKetuaRT = `-- name: DeleteKetuaRT :exec
DELETE FROM ketua_rt WHERE id = ?
`

func (q *Queries) DeleteKetuaRT(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKetuaRT, id)
	return err
}

const deleteLurah = `-- name: DeleteLurah :exec
DELETE FROM lurah WHERE id = ?
`

func (q *Queries) DeleteLurah(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLurah, id)
	return err
}

const deleteSaksiByBerkas = `-- name: DeleteSaksiByBerkas :exec
DELETE FROM saksi_sempadan WHERE berkas_id = ?
`

func (q *Queries) DeleteSaksiByBerkas(ctx context.Context, berkasID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSaksiByBerkas, berkasID)
	return err
}

const ensurePengaturanRow = `-- name: EnsurePengaturanRow :exec

INSERT INTO pengaturan (id, kecamatan, kota, kantor_pertanahan)
VALUES (1, 'Dumai Timur', 'Dumai', 'Kantor Pertanahan Kota Dumai')
ON CONFLICT(id) DO NOTHING
`

// ===== PENGATURAN =====
func (q *Queries) EnsurePengaturanRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensurePengaturanRow)
	return err
}

const getActiveLurahByKelurahan = `-- name: GetActiveLurahByKelurahan :one
SELECT id, kelurahan_id, nama, nip, aktif FROM lurah WHERE kelurahan_id = ? AND aktif = 1 LIMIT 1
`

func (q *Queries) GetActiveLurahByKelurahan(ctx context.Context, kelurahanID int64) (Lurah, error) {
	row := q.db.QueryRowContext(ctx, getActiveLurahByKelurahan, kelurahanID)
	var i Lurah
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
	)
	return i, err
}

const getBerkasDetail = `-- name: GetBerkasDetail :one
SELECT b.id, b.tahun, b.urutan, b.nomor_berkas, b.tanggal_surat, b.p1_nama, b.p1_umur, b.p1_nik, b.p1_pekerjaan, b.p1_alamat, b.p2_nama, b.p2_alamat, b.kelurahan_id, b.jalan_gang, b.rt, b.luas_m2, b.luas_ganti_rugi_m2, b.tgl_pengukuran, b.juru_ukur_kel_id, b.juru_ukur_kec_id, b.lurah_id, b.ketua_rt_id, b.induk_id, b.arsip_lama, b.dup_key, b.dup_override_alasan, b.dup_override_by, b.dup_override_at, b.status, b.created_by, b.created_at, b.updated_at, k.nama AS kelurahan_nama,
    l.nama AS lurah_nama, l.nip AS lurah_nip,
    rt.nama AS ketua_rt_nama, rt.nomor_rt AS ketua_rt_nomor,
    jk.nama AS juru_kel_nama, jk.nip AS juru_kel_nip,
    jc.nama AS juru_kec_nama, jc.nip AS juru_kec_nip,
    i.nomor_berkas AS induk_nomor, i.luas_m2 AS induk_luas
FROM berkas_tanah b
JOIN kelurahan k ON k.id = b.kelurahan_id
LEFT JOIN lurah l ON l.id = b.lurah_id
LEFT JOIN ketua_rt rt ON rt.id = b.ketua_rt_id
LEFT JOIN juru_ukur jk ON jk.id = b.juru_ukur_kel_id
LEFT JOIN juru_ukur jc ON jc.id = b.juru_ukur_kec_id
LEFT JOIN berkas_tanah i ON i.id = b.induk_id
WHERE b.id = ?
`

type GetBerkasDetailRow struct {
	ID                int64           `json:"id"`
	Tahun             int64           `json:"tahun"`
	Urutan            int64           `json:"urutan"`
	NomorBerkas       string          `json:"nomor_berkas"`
	TanggalSurat      string          `json:"tanggal_surat"`
	P1Nama            string          `json:"p1_nama"`
	P1Umur            sql.NullInt64   `json:"p1_umur"`
	P1Nik             string          `json:"p1_nik"`
	P1Pekerjaan       sql.NullString  `json:"p1_pekerjaan"`
	P1Alamat          sql.NullString  `json:"p1_alamat"`
	P2Nama            sql.NullString  `json:"p2_nama"`
	P2Alamat          sql.NullString  `json:"p2_alamat"`
	KelurahanID       int64           `json:"kelurahan_id"`
	JalanGang         string          `json:"jalan_gang"`
	Rt                string          `json:"rt"`
	LuasM2            float64         `json:"luas_m2"`
	LuasGantiRugiM2   sql.NullFloat64 `json:"luas_ganti_rugi_m2"`
	TglPengukuran     sql.NullString  `json:"tgl_pengukuran"`
	JuruUkurKelID     sql.NullInt64   `json:"juru_ukur_kel_id"`
	JuruUkurKecID     sql.NullInt64   `json:"juru_ukur_kec_id"`
	LurahID           sql.NullInt64   `json:"lurah_id"`
	KetuaRtID         sql.NullInt64   `json:"ketua_rt_id"`
	IndukID           sql.NullInt64   `json:"induk_id"`
	ArsipLama         int64           `json:"arsip_lama"`
	DupKey            string          `json:"dup_key"`
	DupOverrideAlasan sql.NullString  `json:"dup_override_alasan"`
	DupOverrideBy     sql.NullInt64   `json:"dup_override_by"`
	DupOverrideAt     sql.NullString  `json:"dup_override_at"`
	Status            string          `json:"status"`
	CreatedBy         sql.NullInt64   `json:"created_by"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
	KelurahanNama     string          `json:"kelurahan_nama"`
	LurahNama         sql.NullString  `json:"lurah_nama"`
	LurahNip          sql.NullString  `json:"lurah_nip"`
	KetuaRtNama       sql.NullString  `json:"ketua_rt_nama"`
	KetuaRtNomor      sql.NullString  `json:"ketua_rt_nomor"`
	JuruKelNama       sql.NullString  `json:"juru_kel_nama"`
	JuruKelNip        sql.NullString  `json:"juru_kel_nip"`
	JuruKecNama       sql.NullString  `json:"juru_kec_nama"`
	JuruKecNip        sql.NullString  `json:"juru_kec_nip"`
	IndukNomor        sql.NullString  `json:"induk_nomor"`
	IndukLuas         sql.NullFloat64 `json:"induk_luas"`
}

func (q *Queries) GetBerkasDetail(ctx context.Context, id int64) (GetBerkasDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getBerkasDetail, id)
	var i GetBerkasDetailRow
	err := row.Scan(
		&i.ID,
		&i.Tahun,
		&i.Urutan,
		&i.NomorBerkas,
		&i.TanggalSurat,
		&i.P1Nama,
		&i.P1Umur,
		&i.P1Nik,
		&i.P1Pekerjaan,
		&i.P1Alamat,
		&i.P2Nama,
		&i.P2Alamat,
		&i.KelurahanID,
		&i.JalanGang,
		&i.Rt,
		&i.LuasM2,
		&i.LuasGantiRugiM2,
		&i.TglPengukuran,
		&i.JuruUkurKelID,
		&i.JuruUkurKecID,
		&i.LurahID,
		&i.KetuaRtID,
		&i.IndukID,
		&i.ArsipLama,
		&i.DupKey,
		&i.DupOverrideAlasan,
		&i.DupOverrideBy,
		&i.DupOverrideAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KelurahanNama,
		&i.LurahNama,
		&i.LurahNip,
		&i.KetuaRtNama,
		&i.KetuaRtNomor,
		&i.JuruKelNama,
		&i.JuruKelNip,
		&i.JuruKecNama,
		&i.JuruKecNip,
		&i.IndukNomor,
		&i.IndukLuas,
	)
	return i, err
}

const getJuruUkur = `-- name: GetJuruUkur :one
SELECT id, tingkat, kelurahan_id, nama, nip, aktif FROM juru_ukur WHERE id = ?
`

func (q *Queries) GetJuruUkur(ctx context.Context, id int64) (JuruUkur, error) {
	row := q.db.QueryRowContext(ctx, getJuruUkur, id)
	var i JuruUkur
	err := row.Scan(
		&i.ID,
		&i.Tingkat,
		&i.KelurahanID,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
	)
	return i, err
}

const getKelurahan = `-- name: GetKelurahan :one
SELECT id, nama, aktif FROM kelurahan WHERE id = ?
`

func (q *Queries) GetKelurahan(ctx context.Context, id int64) (Kelurahan, error) {
	row := q.db.QueryRowContext(ctx, getKelurahan, id)
	var i Kelurahan
	err := row.Scan(&i.ID, &i.Nama, &i.Aktif)
	return i, err
}

const getKetuaRT = `-- name: GetKetuaRT :one
SELECT id, kelurahan_id, nomor_rt, nama, aktif FROM ketua_rt WHERE id = ?
`

func (q *Queries) GetKetuaRT(ctx context.Context, id int64) (KetuaRT, error) {
	row := q.db.QueryRowContext(ctx, getKetuaRT, id)
	var i KetuaRT
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.NomorRt,
		&i.Nama,
		&i.Aktif,
	)
	return i, err
}

const getLurah = `-- name: GetLurah :one
SELECT id, kelurahan_id, nama, nip, aktif FROM lurah WHERE id = ?
`

func (q *Queries) GetLurah(ctx context.Context, id int64) (Lurah, error) {
	row := q.db.QueryRowContext(ctx, getLurah, id)
	var i Lurah
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
	)
	return i, err
}

const getMaxUrutan = `-- name: GetMaxUrutan :one

SELECT COALESCE(MAX(urutan), 0) FROM berkas_tanah WHERE tahun = ?
`

// ===== BERKAS TANAH =====
func (q *Queries) GetMaxUrutan(ctx context.Context, tahun int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxUrutan, tahun)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPengaturan = `-- name: GetPengaturan :one
SELECT id, kecamatan, kota, kantor_pertanahan FROM pengaturan WHERE id = 1
`

func (q *Queries) GetPengaturan(ctx context.Context) (Pengaturan, error) {
	row := q.db.QueryRowContext(ctx, getPengaturan)
	var i Pengaturan
	err := row.Scan(
		&i.ID,
		&i.Kecamatan,
		&i.Kota,
		&i.KantorPertanahan,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, nama, role, must_change_password, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, username, password_hash, nama, role, must_change_password, created_at FROM users WHERE username = ?
`

// ===== USERS =====
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const insertBatas = `-- name: InsertBatas :exec

INSERT INTO batas_tanah (berkas_id, arah, nama_pemilik, nama_normal, panjang_meter)
VALUES (?, ?, ?, ?, ?)
`

type InsertBatasParams struct {
	BerkasID     int64           `json:"berkas_id"`
	Arah         string          `json:"arah"`
	NamaPemilik  string          `json:"nama_pemilik"`
	NamaNormal   string          `json:"nama_normal"`
	PanjangMeter sql.NullFloat64 `json:"panjang_meter"`
}

// ===== BATAS & SAKSI =====
func (q *Queries) InsertBatas(ctx context.Context, arg InsertBatasParams) error {
	_, err := q.db.ExecContext(ctx, insertBatas,
		arg.BerkasID,
		arg.Arah,
		arg.NamaPemilik,
		arg.NamaNormal,
		arg.PanjangMeter,
	)
	return err
}

const insertSaksi = `-- name: InsertSaksi :exec
INSERT INTO saksi_sempadan (berkas_id, urutan, nama) VALUES (?, ?, ?)
`

type InsertSaksiParams struct {
	BerkasID int64  `json:"berkas_id"`
	Urutan   int64  `json:"urutan"`
	Nama     string `json:"nama"`
}

func (q *Queries) InsertSaksi(ctx context.Context, arg InsertSaksiParams) error {
	_, err := q.db.ExecContext(ctx, insertSaksi, arg.BerkasID, arg.Urutan, arg.Nama)
	return err
}

const listBatasByBerkas = `-- name: ListBatasByBerkas :many
SELECT id, berkas_id, arah, nama_pemilik, nama_normal, panjang_meter FROM batas_tanah WHERE berkas_id = ?
ORDER BY CASE arah WHEN 'utara' THEN 1 WHEN 'selatan' THEN 2 WHEN 'barat' THEN 3 ELSE 4 END
`

func (q *Queries) ListBatasByBerkas(ctx context.Context, berkasID int64) ([]BatasTanah, error) {
	rows, err := q.db.QueryContext(ctx, listBatasByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatasTanah{}
	for rows.Next() {
		var i BatasTanah
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Arah,
			&i.NamaPemilik,
			&i.NamaNormal,
			&i.PanjangMeter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBerkas = `-- name: ListBerkas :many
SELECT b.id, b.nomor_berkas, b.tanggal_surat, b.p1_nama, b.p1_nik,
    b.jalan_gang, b.rt, b.luas_m2, b.dup_override_alasan, b.arsip_lama, b.created_at,
    k.nama AS kelurahan_nama
FROM berkas_tanah b
JOIN kelurahan k ON k.id = b.kelurahan_id
WHERE ?1 = '' OR
    b.p1_nama LIKE '%' || ?1 || '%' OR
    b.p1_nik LIKE '%' || ?1 || '%' OR
    b.nomor_berkas LIKE '%' || ?1 || '%' OR
    b.jalan_gang LIKE '%' || ?1 || '%' OR
    k.nama LIKE '%' || ?1 || '%' OR
    EXISTS (SELECT 1 FROM batas_tanah bt
            WHERE bt.berkas_id = b.id AND bt.nama_pemilik LIKE '%' || ?1 || '%')
ORDER BY b.created_at DESC, b.id DESC
LIMIT 500
`

type ListBerkasRow struct {
	ID                int64          `json:"id"`
	NomorBerkas       string         `json:"nomor_berkas"`
	TanggalSurat      string         `json:"tanggal_surat"`
	P1Nama            string         `json:"p1_nama"`
	P1Nik             string         `json:"p1_nik"`
	JalanGang         string         `json:"jalan_gang"`
	Rt                string         `json:"rt"`
	LuasM2            float64        `json:"luas_m2"`
	DupOverrideAlasan sql.NullString `json:"dup_override_alasan"`
	ArsipLama         int64          `json:"arsip_lama"`
	CreatedAt         string         `json:"created_at"`
	KelurahanNama     string         `json:"kelurahan_nama"`
}

func (q *Queries) ListBerkas(ctx context.Context, dollar_1 interface{}) ([]ListBerkasRow, error) {
	rows, err := q.db.QueryContext(ctx, listBerkas, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBerkasRow{}
	for rows.Next() {
		var i ListBerkasRow
		if err := rows.Scan(
			&i.ID,
			&i.NomorBerkas,
			&i.TanggalSurat,
			&i.P1Nama,
			&i.P1Nik,
			&i.JalanGang,
			&i.Rt,
			&i.LuasM2,
			&i.DupOverrideAlasan,
			&i.ArsipLama,
			&i.CreatedAt,
			&i.KelurahanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBerkasByDupPrefix = `-- name: ListBerkasByDupPrefix :many
SELECT b.id, b.nomor_berkas, b.tanggal_surat, b.p1_nama, b.jalan_gang, b.rt,
    b.luas_m2, b.dup_key, k.nama AS kelurahan_nama
FROM berkas_tanah b
JOIN kelurahan k ON k.id = b.kelurahan_id
WHERE b.dup_key LIKE ?1 || '%' AND b.id != ?2
ORDER BY b.created_at DESC
`

type ListBerkasByDupPrefixParams struct {
	Column1 sql.NullString `json:"column_1"`
	ID      int64          `json:"id"`
}

type ListBerkasByDupPrefixRow struct {
	ID            int64   `json:"id"`
	NomorBerkas   string  `json:"nomor_berkas"`
	TanggalSurat  string  `json:"tanggal_surat"`
	P1Nama        string  `json:"p1_nama"`
	JalanGang     string  `json:"jalan_gang"`
	Rt            string  `json:"rt"`
	LuasM2        float64 `json:"luas_m2"`
	DupKey        string  `json:"dup_key"`
	KelurahanNama string  `json:"kelurahan_nama"`
}

func (q *Queries) ListBerkasByDupPrefix(ctx context.Context, arg ListBerkasByDupPrefixParams) ([]ListBerkasByDupPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, listBerkasByDupPrefix, arg.Column1, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBerkasByDupPrefixRow{}
	for rows.Next() {
		var i ListBerkasByDupPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.NomorBerkas,
			&i.TanggalSurat,
			&i.P1Nama,
			&i.JalanGang,
			&i.Rt,
			&i.LuasM2,
			&i.DupKey,
			&i.KelurahanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJuruUkur = `-- name: ListJuruUkur :many

SELECT j.id, j.tingkat, j.kelurahan_id, j.nama, j.nip, j.aktif, k.nama AS kelurahan_nama
FROM juru_ukur j LEFT JOIN kelurahan k ON k.id = j.kelurahan_id
ORDER BY j.tingkat, k.nama, j.nama
`

type ListJuruUkurRow struct {
	ID            int64          `json:"id"`
	Tingkat       string         `json:"tingkat"`
	KelurahanID   sql.NullInt64  `json:"kelurahan_id"`
	Nama          string         `json:"nama"`
	Nip           string         `json:"nip"`
	Aktif         int64          `json:"aktif"`
	KelurahanNama sql.NullString `json:"kelurahan_nama"`
}

// ===== JURU UKUR =====
func (q *Queries) ListJuruUkur(ctx context.Context) ([]ListJuruUkurRow, error) {
	rows, err := q.db.QueryContext(ctx, listJuruUkur)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJuruUkurRow{}
	for rows.Next() {
		var i ListJuruUkurRow
		if err := rows.Scan(
			&i.ID,
			&i.Tingkat,
			&i.KelurahanID,
			&i.Nama,
			&i.Nip,
			&i.Aktif,
			&i.KelurahanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKelurahan = `-- name: ListKelurahan :many
SELECT id, nama, aktif FROM kelurahan ORDER BY nama
`

func (q *Queries) ListKelurahan(ctx context.Context) ([]Kelurahan, error) {
	rows, err := q.db.QueryContext(ctx, listKelurahan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kelurahan{}
	for rows.Next() {
		var i Kelurahan
		if err := rows.Scan(&i.ID, &i.Nama, &i.Aktif); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKetuaRT = `-- name: ListKetuaRT :many

SELECT r.id, r.kelurahan_id, r.nomor_rt, r.nama, r.aktif, k.nama AS kelurahan_nama
FROM ketua_rt r JOIN kelurahan k ON k.id = r.kelurahan_id
ORDER BY k.nama, r.nomor_rt
`

type ListKetuaRTRow struct {
	ID            int64  `json:"id"`
	KelurahanID   int64  `json:"kelurahan_id"`
	NomorRt       string `json:"nomor_rt"`
	Nama          string `json:"nama"`
	Aktif         int64  `json:"aktif"`
	KelurahanNama string `json:"kelurahan_nama"`
}

// ===== KETUA RT =====
func (q *Queries) ListKetuaRT(ctx context.Context) ([]ListKetuaRTRow, error) {
	rows, err := q.db.QueryContext(ctx, listKetuaRT)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKetuaRTRow{}
	for rows.Next() {
		var i ListKetuaRTRow
		if err := rows.Scan(
			&i.ID,
			&i.KelurahanID,
			&i.NomorRt,
			&i.Nama,
			&i.Aktif,
			&i.KelurahanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLurah = `-- name: ListLurah :many

SELECT l.id, l.kelurahan_id, l.nama, l.nip, l.aktif, k.nama AS kelurahan_nama
FROM lurah l JOIN kelurahan k ON k.id = l.kelurahan_id
ORDER BY k.nama, l.aktif DESC, l.nama
`

type ListLurahRow struct {
	ID            int64  `json:"id"`
	KelurahanID   int64  `json:"kelurahan_id"`
	Nama          string `json:"nama"`
	Nip           string `json:"nip"`
	Aktif         int64  `json:"aktif"`
	KelurahanNama string `json:"kelurahan_nama"`
}

// ===== LURAH =====
func (q *Queries) ListLurah(ctx context.Context) ([]ListLurahRow, error) {
	rows, err := q.db.QueryContext(ctx, listLurah)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLurahRow{}
	for rows.Next() {
		var i ListLurahRow
		if err := rows.Scan(
			&i.ID,
			&i.KelurahanID,
			&i.Nama,
			&i.Nip,
			&i.Aktif,
			&i.KelurahanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPecahanByInduk = `-- name: ListPecahanByInduk :many
SELECT id, nomor_berkas, p1_nama, luas_m2 FROM berkas_tanah WHERE induk_id = ? ORDER BY id
`

type ListPecahanByIndukRow struct {
	ID          int64   `json:"id"`
	NomorBerkas string  `json:"nomor_berkas"`
	P1Nama      string  `json:"p1_nama"`
	LuasM2      float64 `json:"luas_m2"`
}

func (q *Queries) ListPecahanByInduk(ctx context.Context, indukID sql.NullInt64) ([]ListPecahanByIndukRow, error) {
	rows, err := q.db.QueryContext(ctx, listPecahanByInduk, indukID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPecahanByIndukRow{}
	for rows.Next() {
		var i ListPecahanByIndukRow
		if err := rows.Scan(
			&i.ID,
			&i.NomorBerkas,
			&i.P1Nama,
			&i.LuasM2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaksiByBerkas = `-- name: ListSaksiByBerkas :many
SELECT id, berkas_id, urutan, nama FROM saksi_sempadan WHERE berkas_id = ? ORDER BY urutan
`

func (q *Queries) ListSaksiByBerkas(ctx context.Context, berkasID int64) ([]SaksiSempadan, error) {
	rows, err := q.db.QueryContext(ctx, listSaksiByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaksiSempadan{}
	for rows.Next() {
		var i SaksiSempadan
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Urutan,
			&i.Nama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBerkas = `-- name: UpdateBerkas :exec
UPDATE berkas_tanah SET
    tanggal_surat = ?,
    p1_nama = ?, p1_umur = ?, p1_nik = ?, p1_pekerjaan = ?, p1_alamat = ?,
    p2_nama = ?, p2_alamat = ?,
    kelurahan_id = ?, jalan_gang = ?, rt = ?, luas_m2 = ?, luas_ganti_rugi_m2 = ?,
    tgl_pengukuran = ?, juru_ukur_kel_id = ?, juru_ukur_kec_id = ?,
    lurah_id = ?, ketua_rt_id = ?, induk_id = ?, arsip_lama = ?,
    dup_key = ?, dup_override_alasan = ?, dup_override_by = ?, dup_override_at = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateBerkasParams struct {
	TanggalSurat      string          `json:"tanggal_surat"`
	P1Nama            string          `json:"p1_nama"`
	P1Umur            sql.NullInt64   `json:"p1_umur"`
	P1Nik             string          `json:"p1_nik"`
	P1Pekerjaan       sql.NullString  `json:"p1_pekerjaan"`
	P1Alamat          sql.NullString  `json:"p1_alamat"`
	P2Nama            sql.NullString  `json:"p2_nama"`
	P2Alamat          sql.NullString  `json:"p2_alamat"`
	KelurahanID       int64           `json:"kelurahan_id"`
	JalanGang         string          `json:"jalan_gang"`
	Rt                string          `json:"rt"`
	LuasM2            float64         `json:"luas_m2"`
	LuasGantiRugiM2   sql.NullFloat64 `json:"luas_ganti_rugi_m2"`
	TglPengukuran     sql.NullString  `json:"tgl_pengukuran"`
	JuruUkurKelID     sql.NullInt64   `json:"juru_ukur_kel_id"`
	JuruUkurKecID     sql.NullInt64   `json:"juru_ukur_kec_id"`
	LurahID           sql.NullInt64   `json:"lurah_id"`
	KetuaRtID         sql.NullInt64   `json:"ketua_rt_id"`
	IndukID           sql.NullInt64   `json:"induk_id"`
	ArsipLama         int64           `json:"arsip_lama"`
	DupKey            string          `json:"dup_key"`
	DupOverrideAlasan sql.NullString  `json:"dup_override_alasan"`
	DupOverrideBy     sql.NullInt64   `json:"dup_override_by"`
	DupOverrideAt     sql.NullString  `json:"dup_override_at"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdateBerkas(ctx context.Context, arg UpdateBerkasParams) error {
	_, err := q.db.ExecContext(ctx, updateBerkas,
		arg.TanggalSurat,
		arg.P1Nama,
		arg.P1Umur,
		arg.P1Nik,
		arg.P1Pekerjaan,
		arg.P1Alamat,
		arg.P2Nama,
		arg.P2Alamat,
		arg.KelurahanID,
		arg.JalanGang,
		arg.Rt,
		arg.LuasM2,
		arg.LuasGantiRugiM2,
		arg.TglPengukuran,
		arg.JuruUkurKelID,
		arg.JuruUkurKecID,
		arg.LurahID,
		arg.KetuaRtID,
		arg.IndukID,
		arg.ArsipLama,
		arg.DupKey,
		arg.DupOverrideAlasan,
		arg.DupOverrideBy,
		arg.DupOverrideAt,
		arg.ID,
	)
	return err
}

const updateJuruUkur = `-- name: UpdateJuruUkur :exec
UPDATE juru_ukur SET tingkat = ?, kelurahan_id = ?, nama = ?, nip = ?, aktif = ? WHERE id = ?
`

type UpdateJuruUkurParams struct {
	Tingkat     string        `json:"tingkat"`
	KelurahanID sql.NullInt64 `json:"kelurahan_id"`
	Nama        string        `json:"nama"`
	Nip         string        `json:"nip"`
	Aktif       int64         `json:"aktif"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdateJuruUkur(ctx context.Context, arg UpdateJuruUkurParams) error {
	_, err := q.db.ExecContext(ctx, updateJuruUkur,
		arg.Tingkat,
		arg.KelurahanID,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updateKelurahan = `-- name: UpdateKelurahan :exec
UPDATE kelurahan SET nama = ?, aktif = ? WHERE id = ?
`

type UpdateKelurahanParams struct {
	Nama  string `json:"nama"`
	Aktif int64  `json:"aktif"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateKelurahan(ctx context.Context, arg UpdateKelurahanParams) error {
	_, err := q.db.ExecContext(ctx, updateKelurahan, arg.Nama, arg.Aktif, arg.ID)
	return err
}

const updateKetuaRT = `-- name: UpdateKetuaRT :exec
UPDATE ketua_rt SET kelurahan_id = ?, nomor_rt = ?, nama = ?, aktif = ? WHERE id = ?
`

type UpdateKetuaRTParams struct {
	KelurahanID int64  `json:"kelurahan_id"`
	NomorRt     string `json:"nomor_rt"`
	Nama        string `json:"nama"`
	Aktif       int64  `json:"aktif"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateKetuaRT(ctx context.Context, arg UpdateKetuaRTParams) error {
	_, err := q.db.ExecContext(ctx, updateKetuaRT,
		arg.KelurahanID,
		arg.NomorRt,
		arg.Nama,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updateLurah = `-- name: UpdateLurah :exec
UPDATE lurah SET kelurahan_id = ?, nama = ?, nip = ?, aktif = ? WHERE id = ?
`

type UpdateLurahParams struct {
	KelurahanID int64  `json:"kelurahan_id"`
	Nama        string `json:"nama"`
	Nip         string `json:"nip"`
	Aktif       int64  `json:"aktif"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLurah(ctx context.Context, arg UpdateLurahParams) error {
	_, err := q.db.ExecContext(ctx, updateLurah,
		arg.KelurahanID,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updatePengaturan = `-- name: UpdatePengaturan :exec
UPDATE pengaturan SET kecamatan = ?, kota = ?, kantor_pertanahan = ? WHERE id = 1
`

type UpdatePengaturanParams struct {
	Kecamatan        sql.NullString `json:"kecamatan"`
	Kota             sql.NullString `json:"kota"`
	KantorPertanahan sql.NullString `json:"kantor_pertanahan"`
}

func (q *Queries) UpdatePengaturan(ctx context.Context, arg UpdatePengaturanParams) error {
	_, err := q.db.ExecContext(ctx, updatePengaturan, arg.Kecamatan, arg.Kota, arg.KantorPertanahan)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, must_change_password = 0 WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
